name: Commit files to git
description: 'Commit all files changed in the workflow back to git'

author: James Nixon <james.nixon@spareroom.co.uk>

inputs:
  commit_message:
    description: Commit message against the commit
    required: true
  github_username:
    description: GitHub username to commit via
    required: true
  github_token:
    description: GitHub token to authenticate the push
    required: true
  forced_files:
    description: Files to force push up to a repository
    required: false

outputs:
  changes_commited:
    description: The changes in the action that were commited

runs:
  using: node16
  main: 'dist/index.js'

branding:
  icon: 'git-commit'
  color: orange
